### ISSUE TITLE
Least-access role voor toegang tot de aws resources

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/mijn-nijmegen#102]
- [ ] lees toegang tot de Lambda functies (om bv de configuratie te kunnen zien)
- [ ] Lees toegang tot de cloudwatch logging van de lambda functies
- [ ] lees toegang tot de cloudwatch Lambda insights (bij voorkeur alleen voor deze lambda's, maar vooralsnog geen probleem als ook de data van andere lambda's te zien is)
- [ ] lees toegang tot de DynamoDb session store
- [ ] GEEN toegang tot de KMS key waarmee DynamoDb encrypt wordt

Deze role is bedoeld voor:
- beheerders van aws omgeving
- pentester

**Comment by joostvanderborg** [comment]
Initiële rol (mijnnijmegen-full-read) toegevoegd in acceptatie-omgeving.

**Comment by joostvanderborg** [comment]
## Least access role per project/applicatie
In Mijn Nijmegen is nu een `mijnnijmegen-full-read`-role aangemaakt, zoals in het eform-project ook een aantal rollen bestaan. Om een group het recht te geven deze rol te assumen moet in de iam-account wat geregeld worden. Dat gaat nu via [aws-account-nijmegen-iam](https://github.com/GemeenteNijmegen/aws-account-nijmegen-iam/blob/production/src/iamStack.ts).  De rol 'leeft' in `gemeentenijmegen-auth-prod`, de groep in `gemeentenijmegen-iam`.

### Opties
1. We kunnen in het project [aws-account-nijmegen-iam](https://github.com/GemeenteNijmegen/aws-account-nijmegen-iam/blob/production/src/iamStack.ts) de rol importeren, daar een group aanmaken die de role mag assumen. Het nadeel is dat daarmee het project afhankelijk wordt van Mijn Nijmegen, en straks elk ander project waar iets met rollen moet.
2. We kunnen de rol daar direct aanmaken, en het assumen regelen. Mijn Nijmegen importeert de rol vervolgens, en hangt er de benodigde policies in het project aan. Daarmee is de afhankelijkheid omgekeerd, maar is het iam-project in ieder geval niet direct afhankelijk van alle projecten. Elk project krijgt 1 afhankelijkheid van het iam-project voor z'n rollen, verder niet. Opzet daarvoor in [draft PR](https://github.com/GemeenteNijmegen/aws-account-nijmegen-iam/pull/7/files)

Open vraag: Hoe zorg je überhaupt dat die rol tussen de twee accounts beschikbaar is/wordt?
