### ISSUE TITLE
KTO plaatsen op Mijn Nijmegen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#1081]

**Comment by joostvanderborg** [comment]
@wvdeeckhout in acceptatie staan voorbeelden van waar/hoe het er nu uit kan zien, in https://github.com/GemeenteNijmegen/mijn-nijmegen/pull/1100 wat screenshots.

**Comment by WietekeNijmegen** [comment]
Topdeskticket die hierbij hoor: M2405 2285 
https://support.irvn.nl/tas/secure/mango/window/3?t=1716802051173
