### ISSUE TITLE
Communicatie over nieuwe Mijn Nijmegen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#110]

**Comment by wvdeeckhout** [comment]
@joostvanderborg  komt er nog een knop <terug> of <naar persoonsgegevens> iod?

**Comment by joostvanderborg** [comment]
Er is nu deze pagina https://www.nijmegen.nl/diensten/mijn-nijmegen/ Vooralsnog zou ik die vooral aanpassen, en als mogelijk in de huidige excellence-schermen mogelijk linken hiernaar. Als Mijn Nijmegen groeit is het misschien de moeite om prominenter op nijmegen.nl wat te gaan doen?

**Comment by wvdeeckhout** [comment]
@joostvanderborg wat een rare vraag van mij zeg. Ik bedoel dat als je in MijnNijmegen zit en kiest voor uitkeringsgegevens, je dan geen knop terug of vorige of home of iets hebt, zodat je weer naar de 1e pagina kan. Dit ook voor als je op persoonsgegevens klikt en dan weer terug wilt.

**Comment by joostvanderborg** [comment]
@wvdeeckhout Aah, dat begreep ik niet helemaal inderdaad. Sinds gisteren is er navigatie toegevoegd, zodat je inderdaad weer terug kunt. Zie #112

**Comment by wvdeeckhout** [comment]
Saskia heeft op de huidige MijnNijmegen omgeving vermeld dat het Mijn zaken onderdeel niet meer actueel is.

**Comment by wvdeeckhout** [comment]
**In de oude omgeving alsvast de melding maken dat deze binnenkort vervalt:** 
De huidige Mijn Nijmegen omgeving start op met Mijn Zaken. Er is geen hoofdpagina/overkoepelende pagina. 
Mijn zaken komt niet terug nog in de nieuwe Mijn Nijmegen. Om hier een vermelding te maken dat er binnenkort een nieuwe omgeving is klopt dan niet helemaal.
Bij het onderdeel Mijn Uitkering kan geen tekst toegevoegd worden, dat is alleen maar een view uit GWS die daar te zien is.
Bij het onderdeel Mijn Gegevens heeft Saskia vermeld dat vanaf 1 juli de gegevens in een nieuwe Mijn Nijmegen te bekijken zijn. Saskia heeft in de oude omgeving alvast een link naar de nieuwe MijnNijmegen geplaatst.

<img width="1199" alt="Screenshot 2022-04-29 at 21 52 48" src="https://user-images.githubusercontent.com/83816236/166061116-b2893c01-7c3a-469a-999a-967481991256.png">

Ik heb haar gevraagd om dit in een nieuw tabblad te openen, zodat je weer terug kan naar de oude Mijn Nijmegen.

**Comment by wvdeeckhout** [comment]
Nieuwe MijnNijmegen opent in een nieuw tabblad.

**Comment by wvdeeckhout** [comment]
Ik sluit deze, is klaar
