### ISSUE TITLE
Uitzoeken wat aan redirects/links aangepast moet worden (link op website, mogelijk menu in oude mijn-omgeving)

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#111]

**Comment by joostvanderborg** [comment]
In oude omgeving zijn inmiddels links opgenomen: https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/110#issuecomment-1113212422 
Bespreken met team Online wat aan redirects kan worden ingesteld. Link website volgt bij livegang.

**Comment by joostvanderborg** [comment]
Redirect van oude portal naar nieuwe kan door Saskia aan Exxellence doorgegeven worden. Na 1-7 alles redirecten. Staat actie bij Team Online om lijst van redirects op te stellen.

**Comment by wvdeeckhout** [comment]
Aanvuling Saskia 9-5-2022: Exxellence laat weten dat het instellen van de redirect 1 minuut tijd kost, kan dus snel gedaan worden zodra we de dag (en tijd) weten. Ik zal dan ook de link op de pagina van Mijn Nijmegen vervangen door de link naar de nieuwe Mijn Nijmegen.
