### ISSUE TITLE
Vullen met issues (in overleg met VNG)

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-nijmegen#1133]
De VNG is bezig met het ontwikkelen van KPI's voor met generiek kunnen meten van de gemeentelijke dienstverlening. Contactpersonen bij VNG zijn Jos van Kester en Hifsa Nasir. In overleg met hen wordt dit gevuld met issues.

**Comment by wvdeeckhout** [comment]
ik laat deze vervallen. Ik plan een afspraak in met VNG en Joost Kamphuis waarna de issues verder aangevuld worden in de epic.
