### ISSUE TITLE
EPIC: vanuit VrijBRP notificeren (deel C)

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-nijmegen#1136]
```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1260
```

**Comment by marnixdessing** [comment]
Afhanklijk van waar het output management componet komt te draaien is er wel of geen DevOps werk nodig.
Als het componenten bij ons draait -> wel werk voor ons, zo niet dan niet.

**Comment by wvdeeckhout** [comment]
Het notificeren vanuit VrijBRP is deels gelukt tijdens de hackathon. De resultaten worden geëvalueerd. Mochten hier nog acties uitkomen, dan wordt dit in een aparte epic opgenomen.
