### ISSUE TITLE
EPIC: architectuur rondom OpenZaak opzetten

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#1141]
Er is nu een openZaak voor VIP in gebruik bij de leverancier Woweb. In het project gaan we ook VrijBRP via een OpenZaak aansluiten. Er is een architectuur nodig om te bepalen of we verschillende openZaken behouden, toe gaan naar 1 OpenZaak en of we een eigen OpenZaak opzetten voor formulieren die geen TSA hebben.

**Comment by marnixdessing** [comment]
Na de bespreking morgen kan deze gesloten worden.

**Comment by wvdeeckhout** [comment]
@marnixdessing kan je aangeven wat er besloten is of waar het besluit te vinden is? Dan kan deze daarna gesloten worden. Dank vast!
