### ISSUE TITLE
[TAAK-VIP] in team bespreken wat de technische impact van taken toevoegen in productie is

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#1174]
We gaan in productie omgeving met VIP taken toevoegen aan Mijn Nijmegen. Vooralsnog is dit de enigste applicatie die hiermee in productie gaat dit jaar. Dit issue is er om de tecnhische gevolgen in beeld te brengen hiervan.

**Comment by joostvanderborg** [comment]
- Takenimplementatie moet worden opgeschoond, komt nog wat werk uit.
- Methode zoals nu geïmplementeerd is verder ok, waar de objecten-API precies gehost is is niet zo'n issue, we kunnen hier flexibel mee omgaan.
- Webformulieren: Het zou mooi zijn als we taak/zaakId mee kunnen geven aan een formulier dat een taak-uitvoering is, maar dit is geen showstopper voor de implementatie.

Advies voor nu:
- objecten-api bij Woweb hosten voor prod, zelf in accp mee gaan testen (bijv. voor VrijBRP)
