### ISSUE TITLE
Tabel-weergave mobiel verbeteren

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#139]

**Comment by joostvanderborg** [comment]
@wvdeeckhout Dit is hoe het werkt als de tabel netjes een header heeft. Dit is snel aangepast en matcht met de component library:
![Image](https://user-images.githubusercontent.com/992731/168556130-64675a9a-2f05-4b1c-abf0-23ef5c8ff6b4.png)

Dit is hoe het is zonder de header: Rustiger maar je verliest het halve scherm aan ruimte. Vereist geen aanpassingen.
![Image](https://user-images.githubusercontent.com/992731/168556289-90b2a43b-845a-4b77-b9b4-54ac8ada179f.png)

Dit is m'n ideaalplaatje, maar vereist wijzigingen in component library, en er is als ik het goed begrepen heb al aardig wat werk in gestoken:
![Image](https://user-images.githubusercontent.com/992731/168556404-f75b9bbc-8405-43fe-8656-cce8e866dcd2.png)

Ik stel voor 1 te kiezen, sluit het beste aan bij wat we al hebben, is snel uit te voeren. Optie 3 neem ik mee in verbeterproces componenten.

**Comment by wvdeeckhout** [comment]
Eens! Dank je wel

**Comment by joostvanderborg** [comment]
Opgelost in https://github.com/GemeenteNijmegen/mijn-uitkering/pull/92 en https://github.com/GemeenteNijmegen/mijn-gegevens/pull/23

**Comment by wvdeeckhout** [comment]
Joost dat ziet er goed uit! Dank je wel
