### ISSUE TITLE
Output uitkeringsapi opschonen? (lettertypes e.d.)

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#140]
- maar ook: statusformulier periode staat als '202205'

**Comment by wvdeeckhout** [comment]
@joostvanderborg deze sluiten?

**Comment by joostvanderborg** [comment]
Ik heb hier nog steeds wel een mening over (de uitkeringsspecificatie is dramatisch te lezen), maar dat moet met afdeling besproken worden denk ik?

**Comment by joostvanderborg** [comment]
Zie nu de epic, dan deze ook sluiten inderdaad.
