### ISSUE TITLE
Team Online: redirecten oude omgeving naar nieuwe

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#150]

**Comment by wvdeeckhout** [comment]
Doen we na 1 juli

**Comment by wvdeeckhout** [comment]
url exxellence formulieren redirecten. Marc heeft de vraag bij Saskia neergelegd om dit op te pakken. Dit bij team online

**Comment by wvdeeckhout** [comment]
reactie Saskia 7-7-2022: Die actie had ik uitgezet bij Exxellence. Omdat onze Exxellence omgeving helemaal uit staat nu lukt dat niet op de gebruikelijke manier. Zij geven aan: Maar misschien is het wel mogelijk dat wij een redirect instellen naar een pagina op jullie website waarop een algemeen tekstje en een link naar nijmegen.nl staat of iets dergelijks. Een beetje op dezelfde manier waarop we een onderhoudspagina op de suite kunnen zetten zodra er een upgrade is (dan verwijzen we ook naar een pagina beschikbaar gesteld door de gemeente op hun eigen hosting, omdat de suite dan uitstaat)
 
Nog geen antwoord gekregen, heb gevraagd of ze al iets mee weten.

**Comment by wvdeeckhout** [comment]
intern oppakken via team online. Wacht dat Saskia terug is van vakantie.

**Comment by wvdeeckhout** [comment]
vraag gesteld aan Saskia, wacht op reactie.

**Comment by wvdeeckhout** [comment]
reactie Saskia: Ik heb geen meldingen tot nu ontvangen dat het niet goed gaat, hoor dat ook niet terug van Hüsran. Sluit ‘m maar.
