### ISSUE TITLE
README van mijn-nijmegen aanpassen

### ISSUE THREAD

**Issue by adgerrits** [GemeenteNijmegen/mijn-nijmegen#159]
Tekst in README.md van mijn-nijmegen is nu: "MIJN Uitkering: Een applicatie voor het bekijken van uitkeringsgegevens binnen de gemeente Nijmegen". Wat verwarrend is omdat mijn-nijmegen meer doet dan alleen uitkeringsgegevens tonen (gevalletje CTRL-C/CTRL-V ?).

**Comment by joostvanderborg** [comment]
Bedankt voor het melden (en onze eerste 'externe' melding!), helemaal terecht. Inmiddels in ieder geval de verwarring verminderd in [deze commit](https://github.com/GemeenteNijmegen/mijn-nijmegen/commit/596602e8557f4d40103501a261feb3df83d17ca4), een wat meer beschrijvende readme gaat nog komen.

**Comment by adgerrits** [comment]
Ha Joost,

 

Graag gedaan.

 

Ik probeer al jaren om binnen de overheid mensen zover te krijgen dat ze wat makkelijker zaken melden zodat je gezamenlijk kunt zorgen dat dingen beter worden. 

Maar dat valt niet mee…. Ik heb zelf ooit voor Common Ground het principe geformuleerd dat we ‘werken in community’s’. Gelukkig zijn er ondertussen een aantal voorbeelden waar dat gebeurt. Maar het in-the-open melden en samen oplossen van vraagstukken blijft een dingetje.

 

Dus… ga ik op een rustig moment weer eens kijken wat voor moois er allemaal uit de Nijmeegse koker komt. En dikke kans dat er dan wel weer een issue volgt 😉 Zeker nou ik heb gemerkt dat er nog naar gekeken wordt ook (want ook dat is niet vanzelfsprekend, ook niet bij Nijmegen waar ik ooit een melding heb gedaan in het opendata-portaal die daar waarschijnlijk nog steeds zielig alleen staat te zijn…)

 

Groeten Ad

 

Van: Joost van der Borg ***@***.***> 
Verzonden: Wednesday, June 29, 2022 11:34 AM
Aan: GemeenteNijmegen/mijn-nijmegen ***@***.***>
CC: Ad Gerrits ***@***.***>; Author ***@***.***>
Onderwerp: Re: [GemeenteNijmegen/mijn-nijmegen] README van mijn-nijmegen aanpassen (Issue #159)

 

Bedankt voor het melden (en onze eerste 'externe' melding!), helemaal terecht. Inmiddels in ieder geval de verwarring verminderd in deze commit <https://github.com/GemeenteNijmegen/mijn-nijmegen/commit/596602e8557f4d40103501a261feb3df83d17ca4> , een wat meer beschrijvende readme gaat nog komen.
