### ISSUE TITLE
EPIC: Mijn Nijmegen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#162]
Vervolg op https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/49

Nog open:
- [x] #124
- [x] #150
- [x] #149

## Doorontwikkeling
- [x] #138

**Comment by wvdeeckhout** [comment]
Deze epic wordt gesloten. Nieuwe klussen voor MijnNijmegen worden in een nieuwe epic opgenomen
