### ISSUE TITLE
Link onderin de zwarte balk werken niet

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#168]
Klik ik op Persoonsgegevens of Uitkeringen (in de zwarte balk onderin) dan wordt de pagina niet gevonden.
Klikken in de menu balk op MijnUitkeringen werkt wel.

![image](https://user-images.githubusercontent.com/83816236/177360419-d7733e61-0440-479d-9269-53f1858dbbfa.png)

**Comment by marnixdessing** [comment]
Aanpassen link in:
- [x] mijn-nijmegen
- [x] mijn-uitkeringen
- [x] mijn-persoonsgevens

**Comment by marnixdessing** [comment]
Uitgerold in prod.
