### ISSUE TITLE
Persoonsgegevens aanvullen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#169]
Persoonsgegevens aanvullen met meer gegevens uit de BRP, zoals geboorteplaats en geheimhouding. Graag even Verder met mij kijken wat er mogelijk is om toe te voegen. Zie ook de MijnGegevens app onder identiteit wat daar getoond wordt.

**Comment by joostvanderborg** [comment]
Het vereist als ik het goed begrijp aanpassingen in de Irma BRP-api. (Daar zitten de velden nu niet in). Dat zou na bepalen wat we willen de volgende stap zijn.

**Comment by wvdeeckhout** [comment]
@joostvanderborg ik haal deze kaart even van onze baaklog. ik ben met Tanja in gesprek om Mijn Nijmegen te prioriteren. Deze staat daar nog niet bij.

**Comment by wvdeeckhout** [comment]
deze sluit ik
