### ISSUE TITLE
X-Ray service implementatie uitzoeken / experimenteren

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-nijmegen#215]
Inclusief eventuele integratie met Servicelens (en misschien synthetics). Dit zijn allemaal cloudwatch 'services' die met x-ray samenwerken.

https://constructs.dev/packages/@aws-cdk/aws-xray/v/1.177.0?lang=typescript

Voorbeeld:
https://dev.to/cdkpatterns/learn-serverless-tracability-with-the-x-ray-tracer-cdk-pattern-lambda-sns-sqs-dynamodb-3457
https://serverlessland.com/patterns/apigw-lambda-dynamodb-xray-cdk

Niet vergeten om juiste rechten mee te geven (policies aan lambda bijv).

CDK code specifiek voor x-ray is nog niet heel nuttig (buiten het aanmaken van groups). Wat wel via CDK geregeld kan worden is voor enkele services (zoals Gateway) traces aanzetten. Dit zorgt ervoor dat er traces worden opgepikt door X-Ray.  Maar meeste dingen gaan toch via de SDK. Wat in het geval van mijn-nijmegen (serverless) ook logisch is.

**Comment by joostvanderborg** [comment]
Waren nog een paar probleempjes met de test op Nijmegen.nl:
- module zat nog niet in de package.json (toegevoegd)
- Daarna gaf het nog een error. Zie https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fmijn-api-api-stack-homefunctionlambdaC6763389-URT0NLdnkGa7/log-events/2022$252F10$252F20$252F$255B$2524LATEST$255D10d822f531084871b12cc74a945f97f7 voor logs. Voor nu even teruggedraaid (Wendy was aan 't testen/demo'en?).

**Comment by MartijnvDijk** [comment]
Foutmelding is nu: "Cannot read property 'captureAWS' of undefined". AWSXRay kan niet worden gevonden (is undefined).
