### ISSUE TITLE
X-Ray implementeren

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-nijmegen#218]

**Comment by wvdeeckhout** [comment]
@MartijnvDijk dit is een issue dat niet onder een epic hangt. Wil je dit beschrijven zodat ik kan toelichten aan mijn opdrachtgever van MijnNijmegen wat dit inhoudt? dank vast

**Comment by wvdeeckhout** [comment]
deze bestaat al
