### ISSUE TITLE
uitzoeken of we weten hoeveel mensen er inloggen met laag en hoeveel met midden.

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#325]
uitzoeken of we kunnen monitoren met welk betrouwbaarheidsniveau een Nijmegenaar inlogt in MijnNijmegen. Met deze informatie kunnen we bepalen wat de impact is van het ophogen van het betrouwbaarheidsniveau.

**Comment by joostvanderborg** [comment]
Signicat geeft het gebruikt betrouwbaarheidsniveau mee: https://developer.signicat.com/broker/signicat-identity-broker/authentication-providers/digid.html#available-attributes

Echter, 'midden' is zowel username + password met sms-token, als mobiele app-gebruik. Er is dus alleen onderscheid te maken tussen:
- laag: alleen gebruikersnaam/wachtwoord
- midden: app óf gebruikersnaam/wachtwoord + sms-token
- substantieel: app + geverifieerd ID (in app)
- hoog: app + ID present (in app)

**Comment by joostvanderborg** [comment]
Na 6 dagen meten Mijn Nijmegen (inclusief een uitbetalingsdag uitkeringen):

|Niveau|aantal|%|
|-----------|------|---|
|substantieel| 457|35|
|midden| 447|34|
|laag| 409|31|

**Comment by wvdeeckhout** [comment]
@joostvanderborg kan je dit nog een keer doorgeven maar dan tot en met vandaag?

**Comment by joostvanderborg** [comment]
Tussen 15-6 en 13-7:
|Niveau|aantal|%|
|-----------|------|---|
|substantieel| 977|38|
|midden| 989|38|
|laag| 614|23|
