### ISSUE TITLE
EPIC: inloggen met Yivi aanzetten voor personen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#328]
**1. epic omschrijving**
Mogelijk maken om met Yivi in te loggen op MijnNijmegen. Het attribuut BSN wordt dan uitgevraagd.
Er wordt een collegevoorstel moet informatiebrief voor de raad opgesteld. Ondertussen zijn we bezig  met een communicatieplan zowel in- als extern.
De lijst met producten en MijnNijmegen is gereed.  

2. Issues

- [x] #368
- [x] #369
- [x] #456
- [x] productiedatum afspreken en communicatie organiseren
- [x] Link naar Yivi-uitlegpagina opnemen in login-pagina Mijn Nijmegen
- [x] #461

**Comment by wvdeeckhout** [comment]
de vraag staat uit bij digitale transformatie of we yivi op 25 mei in productie aan mogen zetten. Wacht op een reactie.

Reactie: 25 mei in productie is prima (eerder mag ook maar moet KCC nog informeren)

**Comment by joostvanderborg** [comment]
Het staat per vandaag live.
