### ISSUE TITLE
signicat vragen of ze IRMA omzetten naar Yivi voor onze aansluiting

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#368]

**Comment by marnixdessing** [comment]
Zo te zien is IRMA omgezet in Yivi bij Signicat. Testen met alleen Yivi als IDP werkte nog niet, even checken hoe dit precies moet. (mijn-nijmegen?)

**Comment by marnixdessing** [comment]
Bij Joost kunnen zien dat het werkt met Yivi dus ik sluit deze
