### ISSUE TITLE
yivi Mijn Nijmegen: - uitvraag op loginpagina

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#460]
Toelichting op welke gegevens we via Yivi uitvragen opnemen op inlogpagina (nu: BSN).

**Comment by joostvanderborg** [comment]
@wvdeeckhout voorbeeld van hoe de yivi-uitvraag eruit kan zien. Getest met uitklap-ding zoals Amsterdam, maar die van ons is veel te lomp voor zoiets.

![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/992731/f9d9bc78-d8a0-4a06-b7f9-518df77154d0)

**Comment by wvdeeckhout** [comment]
Mooi dat het op deze manier kan, ziet er goed uit. wat de tekst betreft: 
ik vind dat 'waarom vragen we uw bsn?' uit het niets vallen. ik zou zoiets doen als

U kunt inloggen door uw BSN (BurgerServiceNummer) vrij te geven. Het BSN is uw eigen persoonsnummer voor contact met de overheid. Om er zeker van te zijn dat alleen de gegevens getoond worden die bij u horen, vragen we u met dit nummer in te loggen in MijnNijmegen.

**Comment by joostvanderborg** [comment]
Iets aangepast: Combi van jouw en mijn tekst gebruikt, het stukje "vragen we u met dit nummer in te loggen in MijnNijmegen" lijkt alsof je je bsn moet gebruiken als een soort wachtwoord. Ik vond het sterk in het Amsterdams voorbeeld dat ze specifiek zijn over waarom díe gegevens voor de dienst, dus dat geprobeerd erin te houden. De formulering in jouw zin zit wat dicht tegen enge cybersecurity-risico's aan, dus wat positiever proberen te formuleren.

![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/992731/b23cbd73-2dbb-4faf-8069-cf01109e7533)

**Comment by wvdeeckhout** [comment]
door persoons- en uitkeringgegevens te noemen, zorg je ervoor dat je dit moet aanpassen als er andere gegevens aan toegevoegd worden. Is het dan beter om persoonlijke gegevens neer te zetten dan de productgegevens?

**Comment by joostvanderborg** [comment]
Da's wel waar, kan op zich wel iets algemener ja. Aan de andere kant: Op het moment ligt het tempo van toevoegen nog niet zo hoog dat dit tekstje aanpassen het probleem wordt ;). Het staat in de koptekst op zich al sinds het begin. Maar omdat het daar staat kan het onderin misschien wel weg. Deze versie staat trouwens in accp nu, dus als je bijv. Leonie om mening wil vragen kun je 'm delen.

**Comment by wvdeeckhout** [comment]
ik spreek haar morgen, dus zal dit vragen. Ik laat het je weten, dank je wel Joost!

**Comment by wvdeeckhout** [comment]
De H1 kop moet worden: Inloggen Mijn Nijmegen
De zin ‘Bekijk uw persoonsgegevens…..’ mag weg.
De zin boven de knoppen moet worden: U kunt kiezen om met DigiD in te loggen of met Yivi.
De zin onder de knoppen moet worden: Door in te loggen geeft u uw BSN (BurgerServiceNummer) door. Dit is een uniek nummer waaraan uw persoonlijke gegevens zijn gekoppeld. Wij vragen uw BSN zodat u alleen uw gegevens ziet. Als u inlogt met DigiD gaat dit vanzelf. Logt u in met Yivi dan vragen wij u in de Yivi-app om uw BSN met ons te delen.
Lees meer over Yivi met link blijft.

**Comment by joostvanderborg** [comment]
Teksten zijn aangepast.
