### ISSUE TITLE
Inloggen met Yivi in productie activeren

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#461]
De release-info staat in productie klaar. Om het live te zetten: Pas de cdk/mijn-nijmegen/useYivi parameter aan in parameter store naar 'true' (kleine letters!), en doe hetzelfde in de login-lambda environment variabele met USE_YIVI (ook op true). Daarmee staat het direct live.

**Comment by wvdeeckhout** [comment]
Kan op 25 mei, dan is er nog tijd om het KCC te instrueren.

**Comment by joostvanderborg** [comment]
@wvdeeckhout dit kan gewoon morgenochtend?

**Comment by wvdeeckhout** [comment]
@joostvanderborg ik heb geen reactie van @marnixdessing ontvangen of er nog problemen zijn geconstateerd. Wat mij betreft kan deze morgenochtend gewoon aan. @marnixdessing mee eens?

**Comment by joostvanderborg** [comment]
Het staat live!
