### ISSUE TITLE
Cloudtrail queries opnemen in CDK ipv handmatig (tbv audit-logging)

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#470]
- Projectspecifiek in het project (Mijn Nijmegen / Webformulieren)
- generieke (als toepasbaar) in aws-monitoring

**Comment by wvdeeckhout** [comment]
@joostvanderborg kan deze weg gezien je opmerkingen?

**Comment by joostvanderborg** [comment]
cloudtrail wordt centraal gelogd in nieuwe LZ, kan inderdaad weg.
