### ISSUE TITLE
Voorbereiding livegang MijnNijmegen & Mijnuitkering

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#49]
Technische issues (WAF, frontend console meldingen).
Release-management inregelen.
- [x] Default release branch wijzigen #46  
- [x] Afspraak IRvN
- [x] #66
- [x] Automatische releases? #47 
- [x] #72
- [x] #57
- [x] #58
- [x] #79
- [x] #88
- [x] quick wins review tweede golf

Voor release:
- [x] #111
- [x] #110
- [x] #123
- [x] #124
- [x] #125
- [x] #150
- [x] #148
- [x] #149

Doorontwikkeling

- [x] #138
- [x] #139

**Comment by wvdeeckhout** [comment]
@joostvanderborg bij het afsluiten van MjinNijmegen weer landen op nijmegen.nl inrichten?

**Comment by wvdeeckhout** [comment]
@joostvanderborg graag de tekst " hier vindt u een overzicht van uw uitkeringen" veranderen. Stem je dit af met Els en/of Saskia?
<img width="837" alt="Screenshot 2022-04-28 at 11 32 56" src="https://user-images.githubusercontent.com/83816236/165723647-34ab9ac4-5994-4822-ae17-ce6b90edad31.png">

**Comment by wvdeeckhout** [comment]
•	De link naar de privacyverklaring werkt niet, moet denk ik [https://www.nijmegen.nl/diensten/privacy/privacyverklaring/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fdiensten%2Fprivacy%2Fprivacyverklaring%2F&data=05%7C01%7Cw.van.den.eeckhout%40nijmegen.nl%7C194d78665fac4ad58e6a08da28f95c28%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C637867348699342758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ySCxbCEIJXv%2BAtnm9nrwmULGeBBn1ezfNplh33BzQec%3D&reserved=0) zijn. En moet daar iets in aangepast worden als de nieuwe Mijn-omgeving er bij komt?

**Comment by wvdeeckhout** [comment]
is het mogelijk om de oude URL op termijn te laten doorlinken, redirecten, naar de nieuwe url? De kans is groot dat mensen deze url opgeslagen hebben vandaar.
Saskia weet niet hoe ze dit kan regelen en heeft een melding bij Exxellence hiervoor gemaakt: I2204 096

**Comment by joostvanderborg** [comment]
Verdere ontwikkeling wordt bijgehouden in #162
