### ISSUE TITLE
onderzoeken of het mogelijk is om vanuit de AWS omgeving de online aanvragen te tonen in MijnNijmegen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#519]
De ingediende aanvragen worden opgeslagen in een Bucket in AWS. is het mogelijk om deze aanvragen te tonen in Mijn Nijmegen? Wetende dat de aanvragen 3 maanden bewaard blijven en dan verwijderd worden. Hoe loopt de klantreis als vervolgens de aanvragen in een TSA worden geregistreerd en afgehandeld mbt statusinformatie?

alle aanvragen zitten in S3
alles wat je indient inzien op MijnNijmegen
eigen backend voor alle aanvragen
ook toegankelijk voor medewerkers?

**Comment by joostvanderborg** [comment]
[Eerste versie ontwerpdocument](https://github.com/GemeenteNijmegen/devops/blob/master/mijnnijmegen/webformulier-aanvragen-in-mijn-nijmegen.md) toegevoegd. User flows nog te tekenen.
