### ISSUE TITLE
Issues toevoegen aan epic (online aanvragen)

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#535]
Epic uitbreiden met Issues nav onderzoek mogelijkheden.

**Comment by joostvanderborg** [comment]
Issues in MVP 1 (opslag van inzendingen) toegevoegd: https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/1 MVP2 (uitgeven basisinformatie / files in Mijn Nijmegen) en 3 (Metadata/ weergave van inzendingen uit JSON-file) volgen nog.
