### ISSUE TITLE
op nijmegen.nl stuk tekst toevoegen ter informatie

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#549]
Wil je dit op Mijn Nijmegen pagina op nijmegen.nl onder de CTA hebben of op de Inloggen Mijn Nijmegen-pagina? Ik vind die laatste logischer. Maar volgens mij kan ik dat niet wijzigen, dat moet Joost doen.

Vanaf 1 augustus kunt u niet meer inloggen via DigiD met uw gebruikersnaam en wachtwoord, u moet dan inloggen met de DigiD-app of in 2 stappen met gebruikersnaam en een sms-code.

**Comment by joostvanderborg** [comment]
In [acceptatie](mijn.accp.nijmegen.nl) neergezet, met iets aangepaste tekst (met het positieve deel begonnen ;)):

![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/992731/bd5e28f9-7745-47b5-8b8b-f185a72bc96c)
![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/992731/a63fc26d-6edc-4893-a241-35d4773223a1)
