### ISSUE TITLE
Uitzoeken welke versie van openzaak kvk wel ondersteund

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-nijmegen#563]

**Comment by joostvanderborg** [comment]
Vermoedelijk vanaf 1.4.0: 
- In de API-standaard is vanaf 1.0.3 een parameter ‘betrokkeneIdentificatie__organisatorischeeenheid__identificatie’ beschikbaar. (https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/zaken-api/1.0.3/src/openapi.yaml#/zaken/zaak_list)
- Die zit er nu nog in, en buiten wat varianten is er niet veel veranderd.
- In Open zaak 1.4.0 is deze api-versie verwerkt. (https://github.com/open-zaak/open-zaak/releases/tag/1.4.0)
