### ISSUE TITLE
Header implementeren

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#590]
Nieuwe header in huisstijl van gemeente Nijmegen (wit, lettertype, etc.) met:
```[tasklist]
### Tasks
- [ ] Logo
- [ ] Naam van ingelogde gebruiker
- [ ] Escape naar Nijmegen.nl
- [ ] Uitlogmogelijkheid
```

**Comment by vladimirdacosta** [comment]
@joostvanderborg 

De header is vinden onder elk ontwerp, onder de naam "Header" -  https://shorturl.at/jmxS9
