### ISSUE TITLE
Sidenavigatie implementeren

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#594]
Menu met icons aan linkerkant (ipv top header menu items)

**Comment by vladimirdacosta** [comment]
@joostvanderborg 

 Navigatie te vinden is onder elk ontwerp, onder de naam "Sidenav" -  https://shorturl.at/jmxS9

**Comment by joostvanderborg** [comment]
staat in acceptatie (alleen op homepage nog)
