### ISSUE TITLE
Notificaties ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#611]
Inwoner krijgt per wijziging een specifieke notificatie in gemeente huisstijl via SMS en/of e-mail met CTA. We kiezen ervoor om de componenten van NL design system te gebruiken hiervoor. 
```[tasklist]
### Tasks
- [x] Inbox/berichtenbox ontwerpen in eigen huisstijl
- [x] Overdragen aan front-end developer
```

**Comment by MariannevanLierop** [comment]
Slecht en lelijk voorbeeld inbox/berichtenbox:

![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/141724497/d009bc57-6af0-4259-80bc-bc8803efd451)

**Comment by MariannevanLierop** [comment]
@joostvanderborg , wil jij hier voorbeeld posten van hackaton?

**Comment by MariannevanLierop** [comment]
@joostvanderborg reminder voorbeeld hackaton

**Comment by joostvanderborg** [comment]
@ruijm1 Hier staan voorbeelden van wat Den Haag in het kader van het project 'mijn zaken' heeft ontworpen. Zowel e-mail als sns-templates. ik zou vooral niet al deze varianten gaan uitpluizen, maar als je globaal kunt kijken wat je van de opzet e.d. vindt: https://www.figma.com/file/6CFtgDTS2oUceGqTWYXhdN/Generieke-Services---MijnDenHaag?type=design&node-id=709-33918&mode=design&t=vwAAfVvZTrSX2eGP-0

**Comment by ruijm1** [comment]
@joostvanderborg ziet er goed uit die notificatievoorbeelden wat betreft content, doen ze netjes in Den Haag. Ik heb een aantal varianten bekeken.

**Comment by vladimirdacosta** [comment]
@joostvanderborg Het prototype is beschikbaar op: https://shorturl.at/kAOV5.
