### ISSUE TITLE
Mijn bedrijfszaken ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#625]
Mijn zaken (binnen Mijn Nijmegen) voor bedrijven en rechtspersonen (Open Zaak bij Woweb/VIP nodig)
```[tasklist]
### Tasks
- [ ] Ontwerpen
- [ ] Ontwerp overleg met contentmanager
- [ ] Overdragen
```

**Comment by vladimirdacosta** [comment]
@joostvanderborg Weet je toevallig welke vooraf ingevoerde gegevens in Mijn Bedrijfszaken verschijnen? Ik neem aan dat dit niet veel verschilt van de gegevens die beschikbaar zijn in MijnZaken voor inwoners.

**Comment by joostvanderborg** [comment]
Bij de KVK kun je zien wat beschikbaar is, dit is een goede startplek: https://developers.kvk.nl/documentation/basisprofiel-api

**Comment by vladimirdacosta** [comment]
Deze issue betreft Mijn Bedrijfszaken. Bij KVK kunnen we enkel de bedrijfsgegevens ontsluiten. Mijn bedrijfsgegevens hebben we al ontworpen.

**Comment by joostvanderborg** [comment]
Ah sorry, er is geen enkel verschil tussen dit en inwoners. Hoeft wat mij betreft niks voor ontworpen, tenzij je andere ideeën hebt :D?
