### ISSUE TITLE
Logo bij YIVI verifier toe laten voegen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#644]
Met SIDN regelen dat we een logo + naam ipv url krijgen bij logins met Yivi.

**Comment by joostvanderborg** [comment]
Sidn:

> Jullie zullen eerst even met signicat moeten afstemmen wat jullie identifier gaat worden. Die moeten jullie nu namelijk nog zelf meesturen met het request naar de Signicat identity broker. Op basis van die identifier (ProviderName) linken wij weer in het scheme een logo en een naam aan jullie verifier.

**Comment by joostvanderborg** [comment]
signicat (support / cc naar accountmanager) gevraagd.

**Comment by joostvanderborg** [comment]
antwoord van signicat:

> Uw ticket met Ticket ID #120187 is bijgewerkt. Zie hieronder de laatste opmerking/reactie inclusief het hele verloop van uw ticket. U kunt antwoorden door te reageren op deze email.
>
>
> <knip> (Signicat)
> Oct 5, 2023, 11:20 GMT+2
>
> Goedemorgen Joost,
> 
> Wij hebben vanuit onze Engineers vernomen dat het wijzigen van de naam geen technische complicaties dient op te leveren. Momenteel is de naam van de identifier MijnNijmegen:
https://authenticatie.nijmegen.nl/broker/config/message-log?creationDate=%7B%22dateFrom%22:%222023-09-19T22:00:00.000Z%22,%22dateTo%22:%222023-09-29T22:00:00.000Z%22%7D&flowId=%225ed4e9d4-6b4a-45be-9944-74a1da693a43%22
> 
> Momenteel is er bij ons nog wel de vraag naar wat jullie dit gewijzigd wensen te hebben.
>
> In afwachting van je reactie,
 
Ik denk dat de identifier gewoon kan blijven bestaan, of anders zou moeten wijzigen naar 'Gemeente Nijmegen'? Het gaat er geloof ik om dat vervolgens SIDN hier weer iets mee kan.

Zie oorspronkelijke mail van SIDN:
> Jullie zullen eerst even met signicat moeten afstemmen wat jullie identifier gaat worden. Die moeten jullie nu namelijk nog zelf meesturen met het request naar de Signicat identity broker. Op basis van die identifier (ProviderName) linken wij weer in het scheme een logo en een naam aan jullie verifier.
>
> We zijn nog bezig om voor Signicat aansluitingen dat proces dicht te timmeren, nu is het nog gebaseerd op afspraken tussen signicat en hun klant. Uiteindelijk zal die providername vastgezet worden bij Signicat zodat partijen die niet meer zelf kunnen meesturen.
>
> Note: Dat is per signicat aansluiting geregeld en partijen mogen niet zomaar een request sturen. Jullie zitten er op bij Amsterdam dus het risico op misbruik is nihil. Maar ook dat willen we uitsluiten.

Het is me niet helemaal helder of Signicat de vraag snapt.

**Comment by wvdeeckhout** [comment]
@marnixdessing is dit mogelijk?
 
‘Deel mijn gegevens met gemeente Nijmegen’
 
‘Je staat op het punt om gegevens te delen met gemeente Nijmegen. Klik op ‘Delen’ om verder te gaan’
 
‘Gelukt. Je gegevens zijn doorgegeven aan gemeente Nijmegen’
 
Dan hoef je niet te benoemen voor welke dienst maar simpelweg ‘gegevens delen met gemeente Nijmegen’, is heel begrijpelijk voor de klant en kan je voor alles gebruiken (Mijn Nijmegen en webformulieren).

**Comment by marnixdessing** [comment]
https://github.com/privacybydesign/pbdf-requestors/pull/18

**Comment by wvdeeckhout** [comment]
@marnixdessing Omdat we steeds meer demo's in het land geven heb ik de vraag of dit ook voor mijn.accp.nijmegen.nl aangepast kan worden.

![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/83816236/c912b778-e4bc-4988-ad4c-c5eaaa6828a0)

**Comment by wvdeeckhout** [comment]
Hetzelfde geldt voor testomgeving formulieren:


![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/83816236/c39f7160-f0c8-4836-b78f-b20b311136d4)
![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/83816236/627f72a3-89b3-4d4f-8a72-27e29dd9a1d8)
