### ISSUE TITLE
NLDS dossier-card implementeren

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#685]
Implementeren van de card-component zoals in Mijn Den Haag gebruikt.

**Comment by joostvanderborg** [comment]
Op https://mijn.accp.nijmegen.nl geïmplementeerd. De wijze van overnemen van componenten is nog niet ideaal.

![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/992731/450c06fc-e60e-461d-9206-0101bdd3addd)

**Comment by MariannevanLierop** [comment]
Correcte link om Mijn zaken te testen = https://mijn.accp.nijmegen.nl/zaken

**Comment by MariannevanLierop** [comment]
Zoals met Joost besproken geeft Myriam geen content feedback op deze acc omgeving maar zet ze al haar content comments in het figma ontwerp van Vladimir :)
