### ISSUE TITLE
Oude inzendingen duurzaam bewaren

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#740]
Opzet:
- In submission storage een SNS topic toevoegen
- De submissionstorage-handler luistert ook hiernaar
- Vanuit webformulieren hiernaar publishing vanuit een lambda
- Deze lambda via api gateway beschikbaar om datum-range aan inzendingen te verwerken.

**Comment by wvdeeckhout** [comment]
@joostvanderborg weet je al tot wanneer je terug kan halen?

**Comment by joostvanderborg** [comment]
Kan maandag naar productie verwacht ik, alles van dan <90 terug kan dan teruggehaald.

**Comment by joostvanderborg** [comment]
Techniek kan vandaag in productie, heb bewaartermijn voor het weekend iets verhoogd.

**Comment by joostvanderborg** [comment]
Inzendingen vanaf 1-8 (eigenlijk 28/29-7) zijn opgeslagen, nieuwere inzendingen worden automatisch opgeslagen. Als er iets mis gaat kan via het nieuwe management-api-endpoint een date-range aan inzendingen opnieuw worden aangeboden aan de storage-oplossing. (Wishlist: specifieke inzendingen opnieuw aanbieden ;)).
