### ISSUE TITLE
Onderscheid tussen inzendingen en zaken

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#752]
Omschrijven welke informatie we hebben bij zaken, en welke bij inzendingen (van formulieren), zodat Myriam en Vladimir hiermee door kan.

https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/749

**Comment by joostvanderborg** [comment]
Excuses, ik zie nu pas dat ik nog iets aan zou leveren. Het onderscheid is vrij eenvoudig:
## Inzending
- Bevat de ingezonden formulier-pdf en evt. bijlages
- Geen statusinformatie bekend (behalve 'ontvangen')
- Geen afdeling o.i.d. gekoppeld
- Wel een 'inzendingsnummer' bekend

## Zaak
- Bevat statusinformatie over de zaak
- Bevat het zaaktype
- Bevat het zaaknummer
- Bevat (nog) geen documenten van de zaak, dit komt wel, en is dan dezelfde set als van de inzending (+ eventueel het besluit)

**Comment by MariannevanLierop** [comment]
@joostvanderborg , zou jij nog 1 voorbeeld willen aanleveren van een 'Inzending'.

**Comment by vladimirdacosta** [comment]
@joostvanderborg 
Het is mij nog niet volledig duidelijk wat precies wordt bedoeld met een "inzending". Kan ik ervan uitgaan dat een inzending verwijst naar documenten, formulieren of andere bijlagen die door de gebruiker zijn ingediend in het kader van een specifieke zaak?

**Comment by joostvanderborg** [comment]
@iamskip 

Ik zal wat meer context geven: 
Uiteindelijk willen we dat elke 'zaak' in Mijn Nijmegen gevolgd kan worden. Een zaak is dan elke aanvraag of ander proces wat een inwoner bij ons start, waar een proces achter zit en een uitkomst aan zit. Denk aan een vergunningverlening, een paspoort-aanvraag, een verhuizing.

Op dit moment kunnen we van maar een klein deel van alle zaken voldoende informatie tonen, omdat pas 1 systeem is aangesloten op Mijn Nijmegen. Van die zaken (APV-vergunning, dingen als evenementenvergunningen, horecavergunning etc.) kunnen we straks alles tonen, zoals ontworpen in de weergave die je al hebt gemaakt.

Alle andere zaken kunnen we nog niet tonen. Om tóch iets van inzicht te geven, kunnen we straks alle **formulierinzendingen** die via app6.nijmegen.nl worden gedaan tonen. (zo'n 120 verschillende soorten aanvragen) Daarvan hebben we alleen geen toegang tot het achterliggende systeem, dus kunnen we alleen tonen:
- Dat er een inzending is geweest
- Welk id-nummer die inzending heeft
- een PDF van de inzending zelf
- eventuele bijlages die de inwoner zelf heeft toegevoegd in het formulier.

Daar kunnen we dus géén status van tonen.

Om het nog iets ingewikkelder te maken: Van **zaken** kunnen we nu wél de status tonen, maar nog niet de bijbehorende documenten, omdat die nog niet gekoppeld zijn. Máár, in de gegevensset **inzendingen** hebben we ook de inzendingen die leiden tot een **zaak**, op dit moment kunnen we die twee alleen nog niet aan elkaar koppelen.

De vraag is nu: Hoe kunnen we al die informatie wel tonen, zorgen dat inwoners snappen dat van **inzendingen** we geen status kunnen tonen, van **zaken** wel, en dat documenten bij een **zaak** mogelijk wel bij de **inzending** te vinden zijn.

Een voorbeeld van een inzending (dit is een testformulier, normaal staat hier begrijpelijker informatie, en hier kunnen dus ook bijlages bij zitten, we hebben als losse gegevens hierbij het ID nummer (TST..., de datum van inzending en de naam van het formulier). Naast de bestanden natuurlijk:
[test-19.pdf](https://github.com/GemeenteNijmegen/mijn-nijmegen/files/13600376/test-19.pdf)
