### ISSUE TITLE
Ontwerp weergave inzendingen implementeren

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#753]
https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/752 + https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/749

**Comment by vladimirdacosta** [comment]
@joostvanderborg 

Link naar het ontwerp: https://shorturl.at/jmxS9

**Comment by MariannevanLierop** [comment]
```[tasklist]
### Tasks
- [ ] Met Wendy overleggen
```

**Comment by joostvanderborg** [comment]
Tekstuele en structuurwijzigingen doorgevoerd zoals uit ontwerp. In het kunnen tonen zit vooral werk aan de backend momenteel.
