### ISSUE TITLE
Logo ontwerpen

### ISSUE THREAD

**Issue by MariannevanLierop** [GemeenteNijmegen/mijn-nijmegen#758]
Alle info in comment in figma: https://www.figma.com/file/MScSuv6Z23Z0LFfCWXAxdY?node-id=65:486&mode=design#586570097
```[tasklist]
### Tasks
- [x] <Logo> | Mijn Nijmegen ontwerpen
- [x] Overdragen aan Joost
```

**Comment by vladimirdacosta** [comment]
![Image](https://github.com/GemeenteNijmegen/mijn-nijmegen/assets/134321433/916301b1-fa58-4827-9ca2-0c084de5d010)

**Comment by vladimirdacosta** [comment]
@joostvanderborg  kan je het logo vanaf hier downloaden of heb je liever via de mail?

**Comment by joostvanderborg** [comment]
Nee dit is prima 👍
