### ISSUE TITLE
Mijn Nijmegen aanpassen voor tonen inzendingen

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-nijmegen#777]
Nadat Vladimir de UX heeft ontworpen, kan Joost dit in Mijn Nijmegen bouwen.

**Comment by wvdeeckhout** [comment]
@joostvanderborg deze bedoel je? Ik krijg het type issue niet gevuld, ook niet na verversen. Zal straks wel verschijnen...

**Comment by joostvanderborg** [comment]
De epic hierboven bedoelde ik 👍

**Comment by joostvanderborg** [comment]
Dit issue uitwerken in delen in deze sprint (en uitvoeren)

**Comment by joostvanderborg** [comment]
Frontend-wijzigingen om ruimte te maken voor ontwerp gedaan. Bezig met implementatie.

**Comment by joostvanderborg** [comment]
Uitgewerkt in losse issues
