### ISSUE TITLE
[Ad Hoc] Certificaten (BRP/uitkeringen) vervangen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-nijmegen#969]
Certificaten mijn-uitkering.nijmegen.nl (prod en acc) verlopen 20-4. Ruim op tijd doen ivm tenantsplitsing!

**Comment by WietekeNijmegen** [comment]
Cnames acc en prod zijn toegevoegd. William heeft de certificaten gegenereerd en ook naar devops mail gestuurd. Op 3 april 16:00 afspraak om samen om te zetten in ESB en bij ons

**Comment by WietekeNijmegen** [comment]
Samen met William de certificaten omgezet van mijn-uitkering en mijn-nijmegen op acceptatie en productie.
In de map met publieke certificaten die wij van William/Sectigo krijgen, is het het bestand die niet in de submappen staat.
- Private keys verwisseld in secrets manager
- Certificaten vervangen in SSM Param store
- Op productie is de lambda opnieuw gestart door handmatig een environment variabele toe te voegen en weer te verwijderen
- William was in de call en heeft gelijktijdig de certificaten vervangen aan de layer 7 kant. In dit geval voor TenT/Bevraging/Irma en data.mijn-nijmegen.nl endpoints.
